FROM node:18-bullseye

RUN apt-get update && apt-get install -y \
  chromium \
  fonts-liberation \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdbus-1-3 \
  libdrm2 \
  libgbm1 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils \
  wget

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx sequelize db:migrate

EXPOSE 3000

CMD ["npm", "run", "start"]